jobs:
- job: Linux_CI
  displayName: 'Linux CI'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix: 
      Python27:
        python: 'python2.7'
      Python36:
        python: 'python3.6'
      Python37:
        python: 'python3.7'
    maxParallel: 3

  variables: {'PYTHONUNBUFFERED': '1'}

  steps:
  - checkout: self
    submodules: recursive

  - script: |
      sudo add-apt-repository -y ppa:deadsnakes/ppa
      sudo apt-get update
      sudo apt-get install -y build-essential
      sudo apt-get install -y $PYTHON ${PYTHON}-dev lib${PYTHON}-dev
      sudo apt-get install -y libgtk-3-dev libjpeg-dev libtiff-dev \
              libsdl2-dev libgstreamer-plugins-base1.0-dev libnotify-dev \
              libsm-dev libwebkit2gtk-4.0-dev libxtst-dev \
              libgl1-mesa-dev libglu1-mesa-dev python-virtualenv
    displayName: 'Install deb package requirements'

  - script: |
      $PYTHON --version 
      curl -O https://bootstrap.pypa.io/get-pip.py
      sudo $PYTHON get-pip.py
      sudo $PYTHON -m pip install -U setuptools wheel 
      sudo $PYTHON -m pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      $PYTHON build.py --jobs=4 dox build_wx
    displayName: 'build wxWidgets'

  - script: |
      $PYTHON build.py --jobs=4 etg --nodoc sip build_py
    displayName: 'build wxPython'

  - script: |
      $PYTHON build.py bdist_wheel
      sudo $PYTHON build.py install
      $PYTHON -c "import wx; print(wx.version());"
    displayName: 'build wheel and test install'
